/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */


#include <bits/stdc++.h>

using namespace std;

class ATeam {
public:
	void solve(istream &in, ostream &out) {
		int n, ans = 0;
		in>>n;
		while(n--) {
			int sum = 0;
			for(int i = 0; i<3; i++) {
				int x;
				in>>x;
				sum+=x;
			}
			ans+=sum>=2;
		}
		out<<ans;
	}
};


int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	ATeam solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
