/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */


#include <bits/stdc++.h>

using namespace std;

class AWayTooLongWords {
public:
	void solve(istream &in, ostream &out) {
		int kase;
		in>>kase;
		while(kase--) {
			string s;
			in>>s;
			if(s.length()>10) {
				out<<s[0]<<s.length()-2<<s[s.length()-1]<<"\n";
			}else {
				out<<s<<"\n";
			}
		}
	}
};


int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	AWayTooLongWords solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
