/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */


#include <bits/stdc++.h>

using namespace std;

class ATheatreSquare {
public:
	void solve(istream &in, ostream &out) {
		long long n, m, a;
		in>>n>>m>>a;
		out<<((n+a-1)/a)*((m+a-1)/a);
	}
};


int main() {
	ios_base::sync_with_stdio(false);
	cin.tie(NULL);
	ATheatreSquare solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
